#!/usr/bin/env node
// dsh-puzzle —— client 打包脚本（零第三方依赖，node 内置 fs）
// 为什么需要它：DSH client bundle 是「单文件直出」（host 把 exports["./client"] 指向的文件
// 原样 serve，无构建步骤；bundle 内 require 只解析 seed word + 已注册 bundle，不支持相对路径）。
// 所以 client 半的「按功能拆分」= 源码拆到 client/src/ 多文件（CJS 风格）+ 本脚本合并成单文件 client.js。
//
// 用法：node client/build.mjs
// 改 client/src/ 后必须重跑，产物 client.js 变化 → client 半热重建 → 刷新页面生效（host 无感）。
//
// 产物形态：window.__ModuleLoader__.load({ id, factory })，factory 内建一个 ~15 行的
// 迷你模块表（__def/__req），每个 src 文件包成 __def('id', function(module, exports, require){...})，
// require('./xxx') 在打包时改写为 require('xxx')（模块 id = 文件名），require('react') 保留走 bundle 的 seed word。
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const SRC = join(HERE, 'src')
const OUT = join(HERE, '..', 'client.js')

// 模块顺序：除 entry 外按文件名排序，entry 最后（懒加载，顺序其实无约束，稳定即可）
const files = readdirSync(SRC).filter((f) => f.endsWith('.js'))
const order = [...files.filter((f) => f !== 'entry.js').sort(), 'entry.js']

const parts = []
for (const f of order) {
  const id = f.slice(0, -3)
  let src = readFileSync(join(SRC, f), 'utf8')
  // require('./xxx') → require('xxx')（模块 id = 文件名）；require('react') 等 seed word 不动
  src = src.replace(/require\((['"])(\.\/[A-Za-z0-9_./-]+)\1\)/g, (_m, q, p) => `require(${q}${p.replace(/^\.\//, '')}${q})`)
  parts.push(`__def(${JSON.stringify(id)}, function (module, exports, require) {\n${src}\n});`)
}

const bundle = `// ⚠️ GENERATED by client/build.mjs —— 本文件是构建产物，不要直接改。
// 手写源码在 client/src/（store / placeholder / quips / game / api / toggle / panel / settings / entry）。
// 改源码后重跑：node client/build.mjs
window.__ModuleLoader__.load({
  id: 'dsh-puzzle-plugin',
  factory: (require) => {
    var react = require('react');
    var __modules = {};
    var __cache = {};
    function __def(id, fn) { __modules[id] = fn; }
    function __req(id) {
      if (id === 'react') return react;
      var m = __cache[id];
      if (m) return m.exports;
      m = { exports: {} };
      __cache[id] = m;
      __modules[id](m, m.exports, __req);
      return m.exports;
    }
${parts.map((p) => '    ' + p.split('\n').join('\n    ')).join('\n')}
    return __req('entry');
  },
});
`

writeFileSync(OUT, bundle, 'utf8')
console.log(`[dsh-puzzle] client bundle rebuilt -> client.js (${parts.length} modules: ${order.join(', ')})`)
